### ISSUE TITLE
Support for request tracking

### ISSUE THREAD

**Issue by nileshmali** [fastify/fastify-reply-from#7]
In ToDo list we have:

> forward the request id to the other peer might require some refactoring because we have to make the req.id unique 

Currently to achieve this I am overriding genReqId of logger and using hyperid to generate unique ids, then I set `x-request-id` header with this value. This allows me to propagate same request-id down to micro service.

My suggestion would be to do this in fastify by setting `x-request-id` or custom request header with hyperid generated value. Currently in fastify request id is generated using simple integer counter.

Please suggest if you have another plan in mind, let me know. I would be happy to submit pull request.

**Comment by mcollina** [comment]
In fastify we can configure the id generator, but only when creating a fastify instance.
In order to use this we might require another additional plugin or configuration, and it might require a new method in fastify.
I think the genReqId function can only be set in the constructor, and we’ll need to add a method to set that from inside a plugin.

cc @delvedor

**Comment by nileshmali** [comment]
Is the plugin right place to create ids?
IMO we should have that built-in with header setting (with custom header name setting. e.g. x-request-id or request-id).

**Comment by mcollina** [comment]
IMHO no. However, this plugin should have the full support for forwarding whatever is the request id.

**Comment by nileshmali** [comment]
Agree. We anyway forward all headers received from source to target. So we could close this and remove todo item.
